FROM httpd:2.4.41-alpine

ENV WAITFORIT_COMMIT 81b1373f17855a4dc21156cfe1694c31d7d1792e
ENV WAITFORIT_SHA256 'b7a04f38de1e51e7455ecf63151c8c7e405bd2d45a2d4e16f6419db737a125d6'
ENV WAITFORIT_PATH /usr/local/bin/wait-for-it.sh

# https://raw.githubusercontent.com/vishnubob/wait-for-it/81b1373f17855a4dc21156cfe1694c31d7d1792e/wait-for-it.sh

RUN wget -O ${WAITFORIT_PATH} "https://raw.githubusercontent.com/vishnubob/wait-for-it/${WAITFORIT_COMMIT}/wait-for-it.sh" \
    && echo "${WAITFORIT_SHA256}  ${WAITFORIT_PATH}" | sha256sum -c \
    && chmod +x ${WAITFORIT_PATH}
# RUN apk add --no-cache bash

CMD ["echo", "done"]
